import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Parent from '../components/body/Parent'
// import styles from '../styles/Home.module.css'
import Header from '../components/header/Header'
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Irancell</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header/>
        <Parent/>
        

    </div>
  )
}

export default Home
